import Joi from "joi";
export const FIRSTNAME = Joi.string().max(20);
export const LASTNAME = Joi.string().max(20);
export const EMAIL = Joi.string().email({ minDomainSegments: 2 }).max(50);
export const PHONE = Joi.string().max(10);
export const DATE = Joi.date().allow("", null);
export const ADDRESS = Joi.string().max(100).allow("", null);
export const PASSWORD = Joi.string().max(100);
export const SHORTSTR = Joi.string().max(50);
export const LONGSTR = Joi.string().max(100);
