### calling registration endpoint

POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{   "firstName": "fhdf",
    "lastName": "fhdf",
    "email": "fhdf",
    "phone": "fhdf",
    "dob": "05/14/2022",
    "address": "fhdf",
    "password": "fhdf"
  }
