### calling registration endpoint

POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{   "firstName": "fhdf",
    "lastName": "fhdf",
    "email": "aa@aa.com",
    "phone": "fhdfsddf",
    "dob": "03/09/2022",
    "address": "fhdf",
    "password":"aaaa"
    
    
}


### logging in

POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{ "email":"aa@aa.com",
"password":"aaaa"
}



#------ categories apis


### post categories

POST http://localhost:8000/api/v1/categories

Content-Type: application/json

{ 
    "status": "active",
    "name":"laptops",
    "parentId":""
}